name: CI

on: [push] #on every branch

jobs:
  #a SAST JOB
  sast_scan:
    name: Run Bandi Scan - used for Python
    runs-on: ubuntu-latest #fresh new envs

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2 
        #Python to install bandit
      - name: Set up Python Install
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
     
      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Scan
        run: bandit -ll -ii -r . -f json -o bandit_scan.json #scan recursively
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: bandit-findings
          path: bandit_scan.json
      #Building Docker Image and Scan using Docker Scout
      #doing on same machine
  image_scan:
      name: Build Image and Run scan
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Setup docker
          uses: docker-practice/actions-setup-docker@v1
          with:
            docker_version: '20.10.7'
        - name: Build Docker Image
          run: docker build -f Dockerfile -t pygoat:latest .
          #docker scout quickview #docker scout cves
      #  - name: Docker Scout Scan
        #  run: | 
        #    curl -sSfL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh 
       #     sh install-scout.sh

         #   echo ${{secrets.REPO_PWD}} || docker login -u ${{secrets.REPO_USER}} --password-stdin
          #  docker scout quickview
           # docker scout cves
         - name: Docker Scout Scan
          uses: docker/scout-action@v1.9.3
          with:
             dockerhub-user:{{secrets.REPO_USER}} 
             dockerhub-password:{{secrets.REPO_PWD}} 
             commad: quickview,cves
             only-severities: critical,high
             sarif-file: scout-report.sarif
         
                
          - name: Upload Artifact
            uses: actions/upload-artifact@v3
            if: always()
            with:
              name: docker-scout-findings
              path: scout-report.sarif

      
